/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing.hotel;

import gui.hotel.MainGUI;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import res.hotel.Reservation;

/**
 *
 * @author Brandon Skrabanek
 */
public class PaymentGUI extends javax.swing.JFrame {

    private int x, y, xx, yy;
    private MainGUI main;
    private Billing bill;
    private BillingGUI billGUI;
    private Reservation res;
    private boolean isExcessiveCleaningBilled = false;
    private boolean isSmokingBilled = false;
    private boolean isHotelDamageBilled = false;
    private boolean hasDiscountBeenApplied = false;

    public PaymentGUI(BillingGUI billGUI, Reservation res, MainGUI main) {
        this.billGUI = billGUI;
        this.res = res;
        this.main = main;
        bill = new Billing(res);
        initComponents();
        fillRes();
        fillBill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dayPriceLabel = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        guestNameLabel = new javax.swing.JLabel();
        guestNameValueLabel = new javax.swing.JLabel();
        roomTypeLabel = new javax.swing.JLabel();
        roomTypeValueLabel = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();
        lengthValueLabel = new javax.swing.JLabel();
        chargesLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        viewPayTotal = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ccPayButton = new javax.swing.JButton();
        cashPayButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        chooseFees = new javax.swing.JComboBox<>();
        addFeeButton = new javax.swing.JButton();
        applyDiscountsButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chooseDiscounts = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        viewPayHotelFee = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        viewDiscountsTotal = new javax.swing.JLabel();
        totalFeesLabel = new javax.swing.JLabel();
        viewFeeTotal = new javax.swing.JLabel();
        chargesByDayButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logoutButton1 = new javax.swing.JButton();

        dayPriceLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        dayPriceLabel.setText("Day Price");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(1, 107, 181));

        guestNameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        guestNameLabel.setText("Guest Name:");

        guestNameValueLabel.setText("N/A");

        roomTypeLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        roomTypeLabel.setText("Room Type:");

        roomTypeValueLabel.setText("N/A");

        lengthLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        lengthLabel.setText("Length of stay:");

        lengthValueLabel.setText("N/A");

        chargesLabel.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        chargesLabel.setText("Charges:");

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel18.setText("Discounts:");

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel19.setText("Total Price:");

        viewPayTotal.setText("$ 0.00");

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel21.setText("Payment Method:");

        ccPayButton.setText("Credit Card");
        ccPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccPayButtonActionPerformed(evt);
            }
        });

        cashPayButton.setText("Cash");
        cashPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPayButtonActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel22.setText("Additional Fees:");

        chooseFees.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clear", "Beverages", "Snack Box", "In-Room Dining", "Per-Pet Stay", "Minibar", "Excessive Cleaning", "Smoking Fee", "Hotel Damage", " " }));
        chooseFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFeesActionPerformed(evt);
            }
        });

        addFeeButton.setText("Add Fee");
        addFeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFeeButtonActionPerformed(evt);
            }
        });

        applyDiscountsButton.setText("Apply Discount");
        applyDiscountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyDiscountsButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel24.setText("Payment");

        chooseDiscounts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clear", "Senior/AARP (55+)", "Military", "AAA Members" }));
        chooseDiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDiscountsActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel25.setText("Discount:");

        viewPayHotelFee.setText("$ 0.00");

        jLabel27.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel27.setText("Hotel Fee:");

        viewDiscountsTotal.setText("$ 0.00");

        totalFeesLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        totalFeesLabel.setText("Total Fees:");

        viewFeeTotal.setText("$ 0.00");
        viewFeeTotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                viewFeeTotalPropertyChange(evt);
            }
        });

        chargesByDayButton.setText("Charges by Day");
        chargesByDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargesByDayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lengthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lengthValueLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(roomTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomTypeValueLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guestNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guestNameValueLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel24))
                    .addComponent(chargesByDayButton)
                    .addComponent(chargesLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalFeesLabel)
                        .addGap(2, 2, 2)
                        .addComponent(viewFeeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewDiscountsTotal)
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseDiscounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(applyDiscountsButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chooseFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addFeeButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(viewPayHotelFee))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(viewPayTotal))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ccPayButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cashPayButton))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestNameLabel)
                    .addComponent(guestNameValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomTypeLabel)
                    .addComponent(roomTypeValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthLabel)
                    .addComponent(lengthValueLabel))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chargesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chargesByDayButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalFeesLabel)
                            .addComponent(viewFeeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewDiscountsTotal)
                            .addComponent(jLabel25))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(viewPayHotelFee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(viewPayTotal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(ccPayButton)
                            .addComponent(cashPayButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(chooseFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addFeeButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(chooseDiscounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(applyDiscountsButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brandon Skrabanek\\Documents\\NetBeansProjects\\GoodStaysHotelApp\\images\\exit.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(5, 10, 46));

        logoutButton1.setText("Logout");
        logoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(logoutButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        billGUI.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void fillRes() {
        if (res != null) {
            DateFormat df = DateFormat.getDateInstance();
            guestNameValueLabel.setText(res.getBoxName());
            roomTypeValueLabel.setText(String.valueOf(res.getRoom().getRoomType()));
            String from = df.format(res.getStayStart());
            String to = df.format(res.getStayEnd());
            String length = from + " - " + to;
            lengthValueLabel.setText(length);
        } else {
            guestNameValueLabel.setText("N/A");
            roomTypeValueLabel.setText("N/A");
            lengthValueLabel.setText("N/A");
        }
    }

    private void ccPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccPayButtonActionPerformed
        String creditCardNumber = (String) JOptionPane.showInputDialog("Enter Credit Card Number");
        String message, title;
        int type;
        try {
            Long creditCardNo = Long.parseLong(creditCardNumber);
            if (creditCardNo > 999) {
                message = "Thank you for your payment of $" + bill.totalBill() + " ending with: XXXX";
                type = JOptionPane.PLAIN_MESSAGE;
                title = "Thank You!";
                ArrayList<Reservation> reservations = main.getMasterReservationList();
                res.getRoom().setIsDirty(false);
                reservations.remove(res);
                this.setVisible(false);
                main.setVisible(true);
            } else {
                throw new Exception();
            }
        } catch (Exception ex) {
            message = "Enter valid credit card number. (Min 4 digits)";
            type = JOptionPane.ERROR_MESSAGE;
            title = "Error!";
        }

        JOptionPane.showMessageDialog(this,
                message,
                title,
                type);

        closeOutRes();

    }//GEN-LAST:event_ccPayButtonActionPerformed

    private void chargesByDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargesByDayButtonActionPerformed
        Date stayStartDate = res.getStayStart();
        Date stayEndDate = res.getStayEnd();
        Calendar stayStart = Calendar.getInstance();
        stayStart.setTime(stayStartDate);

        Calendar stayEnd = Calendar.getInstance();
        stayEnd.setTime(stayEndDate);
        String outputString = "<html>"
                + "<head>"
                + "<style>"
                + "table {"
                + "  font-family: arial, sans-serif;"
                + "  border-collapse: collapse;"
                + "  width: 100%;"
                + "}"
                + ""
                + "td, th {"
                + "  border: 1px solid #dddddd;"
                + "  text-align: left;"
                + "  padding: 8px;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>";

        String title;
        int type;
        LinkedHashMap<String, Double> chargesPerDay = bill.getChargesPerDay();
        if (chargesPerDay != null && chargesPerDay.size() > 0) {
            outputString += "<table>";
            outputString += "<tr>";
            outputString += "<th>Date</th>";
            outputString += "<th>Price</th>";
            outputString += "</tr>";
            for (Map.Entry<String, Double> entry : chargesPerDay.entrySet()) {
                outputString += "<tr>";
                outputString += "<td>" + entry.getKey() + "</td>";
                outputString += "<td>$ " + entry.getValue() + "</td>";
                outputString += "</tr>";
            }
            outputString += "</table>";
            outputString += "</body></html>";
            type = JOptionPane.PLAIN_MESSAGE;
            title = "Charges By Day";
        } else {
            outputString = "Bill not generated yet.";
            type = JOptionPane.ERROR_MESSAGE;
            title = "Error!";
        }

        JOptionPane.showMessageDialog(this,
                outputString,
                title,
                type);
    }//GEN-LAST:event_chargesByDayButtonActionPerformed

    private void closeOutRes() {
        for (int i = 0; i < main.getMasterReservationList().size(); i++) {
            if (main.getMasterReservationList().get(i).getBoxName().equals(res.getBoxName())) {
                main.getMasterReservationList().remove(i);
            }
        }
        res = null;
        fillRes();
        fillBill();
    }

    private void addFeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFeeButtonActionPerformed
        //roomChargesValueLabel.setText("$" + bill.getRes().getRoom().getRoomPrice());
        viewPayHotelFee.setText("$" + bill.getHotelFee());

        if (chooseFees.getSelectedItem().toString().equals("Clear")) {
            bill.setFeeTotal(0.00);
            viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
            isExcessiveCleaningBilled = false;
            isHotelDamageBilled = false;
            isSmokingBilled = false;
        } else if (chooseFees.getSelectedItem().toString().equals("Beverages")) {
            bill.addFee(6.75);
            viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
        } else if (chooseFees.getSelectedItem().toString().equals("Snack Box")) {
            bill.addFee(15.25);
            viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
        } else if (chooseFees.getSelectedItem().toString().equals("In-Room Dining")) {
            bill.addFee(20.50);
            viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
        } else if (chooseFees.getSelectedItem().toString().equals("Minibar")) {
            bill.addFee(35.75);
            viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
        } else if (chooseFees.getSelectedItem().toString().equals("Per-Pet Stay")) {
            bill.addFee(25.00);
            viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
        } else if (chooseFees.getSelectedItem().toString().equals("Excessive Cleaning")) {
            if (!isExcessiveCleaningBilled) {
                bill.addFee(50.00);
                viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
                isExcessiveCleaningBilled = true;
            } else {
                JOptionPane.showMessageDialog(null, "Only one Excessive Cleaning can be billed.", "Warning !!!", JOptionPane.WARNING_MESSAGE);
            }
        } else if (chooseFees.getSelectedItem().toString().equals("Smoking Fee")) {
            if (!isSmokingBilled) {
                bill.addFee(100.00);
                viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
                isSmokingBilled = true;
            } else {
                JOptionPane.showMessageDialog(null, "Only one Smoking Fee can be billed.", "Warning !!!", JOptionPane.WARNING_MESSAGE);
            }
        } else if (chooseFees.getSelectedItem().toString().equals("Hotel Damage")) {
            if (!isHotelDamageBilled) {
                bill.addFee(250.00);
                viewFeeTotal.setText("$" + String.valueOf(bill.getFeeTotal()));
                isHotelDamageBilled = true;
            } else {
                JOptionPane.showMessageDialog(null, "Only one Hotel Damage can be billed.", "Warning !!!", JOptionPane.WARNING_MESSAGE);
            }
        }
        viewPayTotal.setText("$" + bill.totalBill());

    }//GEN-LAST:event_addFeeButtonActionPerformed

    private void chooseFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseFeesActionPerformed

    private void chooseDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDiscountsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseDiscountsActionPerformed

    private void applyDiscountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyDiscountsButtonActionPerformed
        // TODO add your handling code here:
        if (chooseDiscounts.getSelectedItem().toString().equals("Clear")) {
            bill.setDiscount(0.00);
            viewDiscountsTotal.setText("$" + String.valueOf(bill.getDiscount()));
            hasDiscountBeenApplied = false;
        } else if (chooseDiscounts.getSelectedItem().toString().equals("Senior/AARP (55+)")) {
            if (!hasDiscountBeenApplied) {
                bill.addDiscount(5.00);
                viewDiscountsTotal.setText("$" + String.valueOf(bill.getDiscount()));
                hasDiscountBeenApplied = true;
            } else {
                JOptionPane.showMessageDialog(null, "Discount can be only be applied once.", "Warning !!!", JOptionPane.WARNING_MESSAGE);
            }
        } else if (chooseDiscounts.getSelectedItem().toString().equals("Military")) {
            if (!hasDiscountBeenApplied) {
                bill.addDiscount(10.00);
                viewDiscountsTotal.setText("$" + String.valueOf(bill.getDiscount()));
                hasDiscountBeenApplied = true;
            } else {
                JOptionPane.showMessageDialog(null, "Discount can be only be applied once.", "Warning !!!", JOptionPane.WARNING_MESSAGE);
            }
        } else if (chooseDiscounts.getSelectedItem().toString().equals("AAA Members")) {
            if (!hasDiscountBeenApplied) {
                bill.addDiscount(15.00);
                viewDiscountsTotal.setText("$" + String.valueOf(bill.getDiscount()));
                hasDiscountBeenApplied = true;
            } else {
                JOptionPane.showMessageDialog(null, "Discount can be only be applied once.", "Warning !!!", JOptionPane.WARNING_MESSAGE);
            }
        }
        viewPayTotal.setText("$" + bill.totalBill());
    }//GEN-LAST:event_applyDiscountsButtonActionPerformed

    private void cashPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPayButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Thank you for your cash payment of $" + bill.totalBill());
        ArrayList<Reservation> reservations = main.getMasterReservationList();
        res.getRoom().setIsDirty(false);
        reservations.remove(res);
        this.setVisible(false);
        main.setVisible(true);

    }//GEN-LAST:event_cashPayButtonActionPerformed
    private void fillBill() {
        if (res != null) {
            DateFormat df = DateFormat.getDateInstance();

           // roomChargesValueLabel.setText(String.valueOf(bill.getChargesPerDay()));
            viewPayHotelFee.setText(String.valueOf(bill.getHotelFee()));
            viewPayTotal.setText(String.valueOf(bill.totalBill()));
        } else {
           // roomChargesValueLabel.setText("$ 0.00");
            viewPayHotelFee.setText("$ 0.00");
            viewPayTotal.setText("$ 0.00");
        }
    }
    private void viewFeeTotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_viewFeeTotalPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFeeTotalPropertyChange

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        xx = evt.getXOnScreen();
        yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton1ActionPerformed
        this.setVisible(false);
        main.getWelcome().setVisible(true);
    }//GEN-LAST:event_logoutButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFeeButton;
    private javax.swing.JButton applyDiscountsButton;
    private javax.swing.JButton cashPayButton;
    private javax.swing.JButton ccPayButton;
    private javax.swing.JButton chargesByDayButton;
    private javax.swing.JLabel chargesLabel;
    private javax.swing.JComboBox<String> chooseDiscounts;
    private javax.swing.JComboBox<String> chooseFees;
    private java.awt.Label dayPriceLabel;
    private javax.swing.JLabel guestNameLabel;
    private javax.swing.JLabel guestNameValueLabel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JLabel lengthValueLabel;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JLabel roomTypeLabel;
    private javax.swing.JLabel roomTypeValueLabel;
    private javax.swing.JLabel totalFeesLabel;
    private javax.swing.JLabel viewDiscountsTotal;
    private javax.swing.JLabel viewFeeTotal;
    private javax.swing.JLabel viewPayHotelFee;
    private javax.swing.JLabel viewPayTotal;
    // End of variables declaration//GEN-END:variables
}
